/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class TDegree : TBase
{
  private int _classYear;
  private string _diplomaId;

  public int ClassYear
  {
    get
    {
      return _classYear;
    }
    set
    {
      __isset.classYear = true;
      this._classYear = value;
    }
  }

  public string DiplomaId
  {
    get
    {
      return _diplomaId;
    }
    set
    {
      __isset.diplomaId = true;
      this._diplomaId = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool classYear;
    public bool diplomaId;
  }

  public TDegree() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              ClassYear = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              DiplomaId = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("TDegree");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.classYear) {
        field.Name = "classYear";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ClassYear);
        oprot.WriteFieldEnd();
      }
      if (DiplomaId != null && __isset.diplomaId) {
        field.Name = "diplomaId";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(DiplomaId);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("TDegree(");
    bool __first = true;
    if (__isset.classYear) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("ClassYear: ");
      __sb.Append(ClassYear);
    }
    if (DiplomaId != null && __isset.diplomaId) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("DiplomaId: ");
      __sb.Append(DiplomaId);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

