/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum TEducationLevel
{
  AUTODIDACTE = 0,
  CAP = 1,
  BEP = 2,
  BAC = 3,
  BAC2 = 4,
  BAC3 = 5,
  BAC4 = 6,
  BAC5 = 7,
  BAC6 = 8,
  BAC7 = 9,
  BAC8 = 10,
}
