/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class TLanguageSkills : TBase
{
  private Dictionary<string, string> _skills;

  public Dictionary<string, string> Skills
  {
    get
    {
      return _skills;
    }
    set
    {
      __isset.skills = true;
      this._skills = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool skills;
  }

  public TLanguageSkills() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                Skills = new Dictionary<string, string>();
                TMap _map30 = iprot.ReadMapBegin();
                for( int _i31 = 0; _i31 < _map30.Count; ++_i31)
                {
                  string _key32;
                  string _val33;
                  _key32 = iprot.ReadString();
                  _val33 = iprot.ReadString();
                  Skills[_key32] = _val33;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("TLanguageSkills");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Skills != null && __isset.skills) {
        field.Name = "skills";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.String, TType.String, Skills.Count));
          foreach (string _iter34 in Skills.Keys)
          {
            oprot.WriteString(_iter34);
            oprot.WriteString(Skills[_iter34]);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("TLanguageSkills(");
    bool __first = true;
    if (Skills != null && __isset.skills) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Skills: ");
      __sb.Append(Skills);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

