//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFNoCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityAttribute
    {
        public int EntityAttributeId { get; set; }
        public int AttributeId { get; set; }
        public int Column { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string EntityAttributeValue { get; set; }
        public int EntityId { get; set; }
        public bool IsDeleted { get; set; }
        public int Row { get; set; }
        public int UpdatedByUserId { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
